"""initial

Revision ID: 87ac2eb49c84
Revises: 
Create Date: 2026-06-20 03:23:22.669667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ac2eb49c84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('total_marks', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_subject'), ['subject'], unique=False)

    op.create_table('students',
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('class_grade', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_student_id'), ['student_id'], unique=False)

    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('model_answer', sa.Text(), nullable=False),
    sa.Column('max_marks', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_questions_id'), ['id'], unique=False)

    op.create_table('submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('num_questions', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('max_total_marks', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_submission_id'), ['submission_id'], unique=False)

    op.create_table('answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('marks_obtained', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('max_marks', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('similarity_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('correct_answer_text', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_answer_id'), ['answer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_answer_id'))

    op.drop_table('answers')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_submission_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_questions_id'))

    op.drop_table('assessment_questions')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_id'))

    op.drop_table('students')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_subject'))
        batch_op.drop_index(batch_op.f('ix_assessments_id'))

    op.drop_table('assessments')
    # ### end Alembic commands ###
